# file: roles/perl/tasks/main.yml
---

- name    : Download tar file of the latest perl
  shell   : wget http://www.cpan.org/src/5.0/perl-{{perl_ver}}.tar.gz -P {{src_dir}}
- name    : Decompress perl tar file.
  command : chdir={{src_dir}} tar zxvf perl-{{perl_ver}}.tar.gz
- name    : Configuration and make install
  command : sudo {{item}} chdir={{src_dir}}/perl-{{perl_ver}}
  with_items:
    - ./configure.gnu –prefix=/usr/local/perl
    - make
    - make install
