- hosts : timakinbox
  user  : vagrant
  sudo  : yes
  vars:
    root_db_password: password
  tasks :
    - name    : Install Basic libs
      yum     : name={{ item }} state=installed
      with_items:
        - gcc
        - make
        - git
    - name    : Install Apache
      yum     : name=httpd state=installed
    - name    : Change the setting of Apache
      service : name=httpd state=started enabled=yes
    - name    : Install MySQL packages
      yum     : name={{ item }} state=installed
      with_items:
        - mysql
        - mysql-server
        - mysql-devel
        - MySQL-python
    - name    : Start MySQL job process
      service : name=mysqld state=started enabled=yes
    - template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600
    - mysql_user: name=root host={{item}} password={{root_db_password}}
      with_items:
        - 127.0.0.1
        - localhost

    - name    : Export PATH
      shell   : echo "export PATH=$PATH:{{ item }}/bin" >> /home/vagrant/.bashrc
      with_items:
        - /usr/local
        - /home/vagrant/perl5

  roles:
    - {role: perl, perl_ver: 5.20.1}
    - cpanm
